# Generated by Django 4.0.2 on 2022-05-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('walletAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
